### ISSUE TITLE
Add a message to request a missing extension

### ISSUE THREAD

**Issue by ahachete** [postgres-anywhere/pga.sh#14]
We should have a small box like an "informational sign" saying something similar to:

"Don't find the extension you are looking for? Please let us know." where the last sentence is a link to GitHub to file an issue of a given type (template).

This issue is contingent on #13

**Comment by jjmaestro** [comment]
This call for action should also be in the "filter extensions" result, e.g.

![image](https://github.com/user-attachments/assets/c06471d8-71b8-4ead-97d8-c59125e80791)

Then filtering for `foobar`:
![image](https://github.com/user-attachments/assets/80ff345b-39c9-4018-8531-914a8d572e87)


I think the "No extensions have been found" could also have the "This extension is not available for `${flavor} ${flavorMajor}.{flavorMinor}`" message from #13 and something like a "Please let us know if you think we should have it!" call-for-action that opens a GH issue.

**Comment by lgarciaog** [comment]
I think this must be shown ALWAYS under the extensions list, since it applies to both, cases where the user is filtering extensions or when the user reaches the bottom of the list looking for an extension that's not available.

Here's what it looks like in both cases:

**At the bottom:**

<img width="758" alt="image" src="https://github.com/user-attachments/assets/e0e1db87-7c66-4e5d-a0a7-449bab81e89a" />

**When filtering:**

<img width="732" alt="image" src="https://github.com/user-attachments/assets/2b8f3644-624e-4c56-81d9-d180c7424d04" />

**Comment by lgarciaog** [comment]
Closing since this has already been implemented
